# Generated by Django 2.1.7 on 2019-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(2, 'zabawki'), (0, 'ubrania, które nadają się do użytku'), (1, 'ubrania, do wyrzucenia'), (3, 'kasiążki'), (4, 'inne')])),
                ('institution', models.IntegerField(choices=[(0, 'Dbam o Zdrowie'), (4, 'Mam marzenie'), (1, 'Dla dzieci'), (3, 'Walka z rakiem "Yasuo mid"'), (2, 'Bez domu')])),
            ],
        ),
    ]
