# Generated by Django 2.1.7 on 2019-03-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'ubrania, które nadają się do użytku'), (2, 'zabawki'), (1, 'ubrania, do wyrzucenia'), (3, 'kasiążki'), (4, 'inne')])),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hour', models.TimeField()),
                ('more_info', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
