# Generated by Django 2.1.7 on 2019-03-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='type',
            field=models.IntegerField(choices=[(2, 'zabawki'), (3, 'kasiążki'), (4, 'inne'), (0, 'ubrania, które nadają się do użytku'), (1, 'ubrania, do wyrzucenia')]),
        ),
    ]
