# Generated by Django 2.1.7 on 2019-03-25 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('give', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('more_info', models.CharField(blank=True, max_length=255)),
                ('gift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gifts',
            name='localization',
            field=models.IntegerField(choices=[(2, 'Wrocław'), (3, 'Poznań'), (4, 'Gdańsk'), (1, 'Warszawa'), (0, 'Niezależne')], default=0),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='institution',
            field=models.IntegerField(choices=[(2, 'Bez domu'), (3, 'Walka z rakiem "Yasuo mid"'), (4, 'Mam marzenie'), (0, 'Dbam o Zdrowie'), (1, 'Dla dzieci')]),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='type',
            field=models.IntegerField(choices=[(0, 'ubrania, które nadają się do użytku'), (4, 'inne'), (1, 'ubrania, do wyrzucenia'), (3, 'kasiążki'), (2, 'zabawki')]),
        ),
    ]
